/**
 * Open Civic Signature Protocol — core protocol types (provider-agnostic).
 *
 * These types form LAYER B (the reusable protocol). They deliberately contain
 * NO Voice-of-Gudalur-specific business logic and no provider-specific types.
 * A provider adapter (e.g. CAMARA Number Verification) implements the
 * MobileIdentityVerifier interface; the signature engine depends only on this
 * module.
 *
 * Semantics:
 *  - A "subject" is the provider-issued identifier for a verified identity
 *    (e.g. a phone number a CAMARA Number Verification endpoint confirms).
 *  - A subject is NEVER stored, logged, or transmitted beyond the adapter.
 *    The engine keeps only `identity_key_hash = HMAC-SHA-256(VERIFICATION_IDENTITY_SECRET,
 *    canonical_subject)`.
 *  - An assurance level describes what was actually verified — NOT proof of a
 *    unique human being.
 */

/** Assurance levels. Levels are ordinal; a level N claim never implies N-1 is
 *  absent, and never implies a unique biological human. */
export enum AssuranceLevel {
  /** No verification performed. */
  NONE = 0,
  /** Anti-bot only (e.g. Turnstile / signed challenge passes). */
  ANTI_BOT = 1,
  /** Self-asserted mobile identity (user claims/enters the number; consent recorded). */
  SELF_ASSERTED_MOBILE = 2,
  /** Network-verified mobile identity (operator-issued proof of number control). */
  NETWORK_VERIFIED = 3,
  /** Trusted verifiable credential (external VC / DigiLocker-style document proof). */
  VERIFIABLE_CREDENTIAL = 4,
}

/** Human-readable assurance claim — the ONLY claim a UI may make. */
export const ASSURANCE_CLAIMS: Record<AssuranceLevel, string> = {
  [AssuranceLevel.NONE]: 'Unverified',
  [AssuranceLevel.ANTI_BOT]: 'Anti-bot verified',
  [AssuranceLevel.SELF_ASSERTED_MOBILE]: 'Self-asserted mobile identity — the person confirmed they control this number',
  [AssuranceLevel.NETWORK_VERIFIED]: 'Network-verified mobile identity — the operator confirmed this number',
  [AssuranceLevel.VERIFIABLE_CREDENTIAL]: 'Trusted verifiable credential presented',
};

export const ASSURANCE_LEVEL_MAX = AssuranceLevel.VERIFIABLE_CREDENTIAL;

/** Persisted lifecycle of a verification transaction. */
export enum VerificationState {
  CREATED = 'CREATED',     // transaction allocated, not yet acted upon
  STARTED = 'STARTED',     // provider interaction begun
  VERIFIED = 'VERIFIED',   // verification succeeded (result recorded)
  FAILED = 'FAILED',       // verification failed (deterministic; may retry with a new tx)
  EXPIRED = 'EXPIRED',     // created_at exceeded expires_at
  CONSUMED = 'CONSUMED',   // verification bound to a completed signature
}
/** What a provider can do. Exposed via GET /api/civic/capabilities and rendered
 *  on the /trust page so that claims are transparent and data-driven. */
export interface VerificationCapabilities {
  provider: IdentityProviderName;
  /** Highest assurance level this provider can currently reach. */
  maxAssurance: AssuranceLevel;
  /** Production mode (true = real operator/network credentials configured). */
  production: boolean;
  /** Sandbox mode (true = provider sandbox configured / usable). */
  sandbox: boolean;
  /** Human-readable description used on the trust page. */
  description: string;
}

/** Canonicalized subject + derived privacy hash (raw subject is dropped ASAP). */
export interface NormalizedSubject {
  /** Canonical form of the provider subject (e.g. 9876543210 for an Indian MSISDN). */
  canonical: string;
  /** HMAC-SHA-256(VERIFICATION_IDENTITY_SECRET, domain:canonical) — the ONLY
   *  subject-derived value the engine persists. */
  identityKeyHash: string;
  /** Short, non-reversible log/correlation prefix. */
  logPrefix: string;
}

/** Request handed to a provider adapter. Providers MUST NOT receive the raw
 *  subject unless they need it to perform verification (CAMARA does); the
 *  adapter is responsible for not persisting or logging it. */
export interface VerificationRequest {
  /** Public transaction reference generated by the engine. */
  transactionRef: string;
  /** Correlation ID of the originating HTTP request (never the subject). */
  requestId: string;
  /** Canonical subject (e.g. normalized mobile). Provider-scope only. */
  subject: string;
  /** Desired minimum assurance level for this verification. */
  requestedAssurance: AssuranceLevel;
  /** Opaque callback data the adapter may echo (never PII). */
  callbackData?: Record<string, string>;
}

/** Result of a provider verification attempt. */
export interface VerificationResult {
  ok: boolean;
  /**
   * Provider's own verification/transaction reference. PERSISTED — must be a
   * non-identifying opaque token, NOT the subject.
   */
  providerRef?: string;
  /** Integrity reference over the provider's signed/raw response payload
   *  (e.g. HMAC over the raw JSON), enabling non-repudiation of a recorded
   *  VERIFIED result without storing the payload itself. */
  resultReference?: string;
  /** Highest assurance level this provider can claim had a positive outcome. */
  assurance: AssuranceLevel;
  /** Client-safe failure reason when ok === false. */
  failureReason?: VerificationFailureReason;
  /** Provider assertion the subject was NOT verified (mismatch) — used to
   *  record failure without storing the subject. */
  mismatch?: boolean;
}

/** The provider interface. Implementations MUST be stateless w.r.t. the
 *  transaction lifecycle — all state lives in identity_verification_transactions. */
export interface MobileIdentityVerifier {
  /** Static capability description (env-driven — fail closed on missing config). */
  getCapabilities(): VerificationCapabilities;
  /**
   * Perform verification for a subject.
   * Must throw typed ProviderError (see providers/errors.ts) on transport/config
   * failures; return { ok:false, ... } for a definitive "not verified".
   * Implementations MUST NOT store/log the raw subject.
   */
  verify(request: VerificationRequest): Promise<VerificationResult>;
  /** Provider-specific start step, e.g. CAMARA's operator-consent redirect.
   *  Returns undefined when there is no interactive step. */
  start?(request: VerificationRequest): Promise<{ redirectUrl?: string; providerRef?: string } | undefined>;
}

/** Provider registry entry. */
export interface ProviderDescriptor {
  name: IdentityProviderName;
  verifier: MobileIdentityVerifier;
}

export const VERIFICATION_TX_TTL_SECONDS = Number(process.env.VERIFICATION_TX_TTL_SECONDS ?? 10 * 60);

/** Prefix used for the public transaction reference (e.g. VOG-VT-…). */
export const TRANSACTION_REF_PREFIX = process.env.VERIFICATION_TX_PREFIX || 'VOG-VT';

export const VERIFICATION_STATES: VerificationState[] = [
  VerificationState.CREATED,
  VerificationState.STARTED,
  VerificationState.VERIFIED,
  VerificationState.FAILED,
  VerificationState.EXPIRED,
  VerificationState.CONSUMED,
];

/** Stable (client-safe) failure reasons — never leak provider internals. */
export type VerificationFailureReason =
  | 'provider_unavailable'
  | 'provider_error'
  | 'provider_timeout'
  | 'verification_mismatch'
  | 'invalid_request'
  | 'expired'
  | 'malformed_response'
  | 'invalid_token'
  | 'token_expired'
  | 'not_verified';

/** Stable (client-safe) provider names. */
export type IdentityProviderName = 'self-asserted' | 'camara' | 'turnstile';
