import { test, expect, type Page } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

/**
 * Aadhaar scan E2E — proves the REAL browser pipeline end-to-end:
 *
 *   PNG fixture (a genuine QR code of a synthetic 2022 "V2" Aadhaar
 *   secure-QR payload, Version 30 / 145 modules — same density as a real
 *   card) → upload through the actual file input OR fed through a fake
 *   camera stream → decodePhotoQr / decodeVideoFrame (BarcodeDetector →
 *   ZBar-wasm → jsQR) → decodeAadhaarAsync → decoded fields on screen.
 *
 * The fixture is generated by `python scripts/make_test_qr.py` and committed
 * so the suite needs no python at runtime. No real PII anywhere.
 */
const FIXTURE = path.join(fileURLToPath(new URL('.', import.meta.url)), 'fixtures', 'aadhaar_secure_qr.png');
const FIXTURE_URL = '/__test_fixture__/aadhaar_secure_qr.png';

/** Open the app and the register modal (header brand → openIdModal). */
async function openRegisterModal(page: Page) {
  await page.goto('/', { waitUntil: 'domcontentloaded' });
  await page.waitForSelector('#root > *', { timeout: 30_000 });
  await page.locator('header .cursor-pointer').first().click();
  await expect(page.getByTestId('photo-scan-button')).toBeVisible({ timeout: 15_000 });
}

/** Serve the QR fixture to the page over a routed URL. */
async function serveFixture(page: Page) {
  await page.route(FIXTURE_URL, (route) =>
    route.fulfill({ path: FIXTURE, contentType: 'image/png' }),
  );
}

test.describe('Aadhaar QR scan', () => {
  test('photo scan — real Aadhaar secure-QR PNG decodes to resident data', async ({ page }) => {
    await openRegisterModal(page);

    // Upload the real QR image through the app's actual photo-scan input.
    await page.setInputFiles('input#qr-file-input', FIXTURE);

    // decodePhotoQr (multi-engine + scale ladder) runs, then decodeAadhaarAsync
    // parses the V2 payload → the Verified screen must show the fields.
    await expect(page.getByTestId('decoded-name')).toHaveText('Gudalur Test', { timeout: 45_000 });
    await expect(page.getByTestId('decoded-last4')).toContainText('1234');
    await expect(page.getByTestId('decoded-address')).toContainText('Nilgiris');
    await expect(page.getByTestId('decoded-address')).toContainText('643212');
    await expect(page.getByTestId('phone-input')).toBeVisible();
    // Complete Registration stays disabled until a 10-digit phone is typed.
    await expect(page.getByTestId('complete-registration')).toBeDisabled();
  });

  test('live camera — canvas-fed fake stream decodes the Aadhaar QR', async ({ page, context }) => {
    test.setTimeout(120_000);
    await context.grantPermissions(['camera'], { origin: 'http://localhost:3000' });
    await serveFixture(page);

    // Replace getUserMedia with a canvas video source that shows the QR PNG.
    // The app's own decode loop (decodeVideoFrame → ZBar-wasm/jsQR) then reads
    // it in real time — exactly what a phone camera produces.
    await page.addInitScript((url) => {
      const md = navigator.mediaDevices;
      if (!md) return;
      const original = md.getUserMedia.bind(md);
      md.getUserMedia = async (constraints: MediaStreamConstraints) => {
        const wantsCamera =
          (constraints as MediaStreamConstraints).video !== undefined &&
          (constraints as MediaStreamConstraints).video !== false;
        if (!wantsCamera) return original(constraints);
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d')!;
        try {
          const res = await fetch(url);
          const blob = await res.blob();
          const bmp = await createImageBitmap(blob);
          canvas.width = bmp.width;
          canvas.height = bmp.height;
          ctx.drawImage(bmp, 0, 0);
        } catch (e) {
          console.error('fixture load failed', e);
        }
        return canvas.captureStream(15) as unknown as MediaStream;
      };
    }, FIXTURE_URL);

    await openRegisterModal(page);
    await page.getByTestId('open-camera').click();

    // The scan loop decodes frames every ~150-300ms; a hit lands on the
    // Verified screen with the decoded fields.
    await expect(page.getByTestId('decoded-name')).toHaveText('Gudalur Test', { timeout: 90_000 });
    await expect(page.getByTestId('decoded-last4')).toContainText('1234');
  });
});