/**
 * Voice of Gudalur — snapshot-first client fetch.
 *
 * Public read endpoints have CDN-served static snapshots under /data/*.json
 * (generated by scripts/exportSnapshot.ts). Reading the snapshot costs ZERO
 * function invocations and ZERO database reads — the entire free-tier win for
 * a crowd. On ANY snapshot failure (missing/expired/HTML), fall back to the
 * live API so the data is never lost.
 *
 * Snapshots are seconds-stale by design (regenerated on writes + a cron). Call
 * sites that NEED realtime should keep using the live API.
 */
export async function snapshotOrLive<T>(
  snapshotPath: string,
  liveFetch: () => Promise<T>,
  opts: { acceptStaleMs?: number } = {},
): Promise<T> {
  try {
    // Bounded: never let the snapshot lookup hang the page.
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), 2500);
    const res = await fetch(snapshotPath, { signal: ctrl.signal, credentials: 'omit' });
    clearTimeout(t);
    if (!res.ok) throw new Error(`snapshot ${res.status}`);
    const text = await res.text();
    if (/^\s*<(!doctype|html)/i.test(text)) throw new Error('snapshot is HTML (not deployed)');
    const data = JSON.parse(text);
    const ageMs = Date.now() - new Date(data.updatedAt || data.generatedAt || 0).getTime();
    if (opts.acceptStaleMs && ageMs > opts.acceptStaleMs) throw new Error('snapshot too stale');
    return data as T;
  } catch {
    return liveFetch();
  }
}