import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ta' | 'ml' | 'kn';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Brand & Navigation
    'brand.title': 'VOICE OF GUDALUR',
    'brand.tagline': 'One Place. Many Communities. One Connected People.',
    'nav.manifesto': 'Right to Life Manifesto',
    'nav.home': 'Manifesto',
    'nav.hub': 'Civic Hub & Pulse',
    'nav.places': 'Localities',
    'nav.live': 'Gudalur Live',
    'nav.alerts': 'Urgent Alerts',
    'nav.issues': 'Civic Issues',
    'nav.wildlife': 'Wildlife Hub',
    'nav.petitions': 'Act For Gudalur',
    'nav.government': 'Govt Grievances',
    'nav.bus': 'Bus Timings',
    'nav.services': 'Services',
    'nav.story': 'The Story',
    'nav.guide': 'AI Civic Guide',
    'nav.id': 'Gudalur ID',
    'nav.admin': 'Console',
    'nav.join': 'Join Gudalur',

    // Hero Section
    'hero.badge': 'Living Intelligence & Civic Action Platform',
    'hero.headline': 'Gudalur United.',
    'hero.subheadline': 'From O\'Valley to Nadugani, from Thorapalli to Devala — connect with your locality, track real civic problems, receive verified emergency alerts, and organize lawful citizen action.',
    'hero.join_btn': 'Get Your Gudalur ID',
    'hero.explore_map': 'Explore Localities',
    'hero.active_residents': 'Verified Residents',
    'hero.verified_localities': 'Verified Localities',
    'hero.active_petitions': 'Active Civic Petitions',
    'hero.resolved_issues': 'Issues Documented',

    // Gudalur Live
    'live.title': 'Gudalur Live',
    'live.subtitle': 'Real-time environmental, mobility and emergency pulse of the Nilgiris western plateau',
    'live.weather_temp': 'Temperature',
    'live.weather_air': 'Air Quality (AQI)',
    'live.weather_rain': 'Rain Probability',
    'live.weather_humidity': 'Humidity',
    'live.weather_wind': 'Wind Speed',
    'live.ghat_status': 'Ghat Roads Status',
    'live.night_traffic': 'Mudumalai Night Ban: 9:00 PM – 6:00 AM Active',
    'live.emergency_hotline': '24x7 Nilgiris Emergency Lifeline',

    // Localities
    'places.title': 'Explore Gudalur Localities',
    'places.subtitle': 'Every neighborhood is a living community node. Discover local services, coordinators, active civic demands, and join your place.',
    'places.search_placeholder': 'Search locality (e.g. SS Nagar, First Mile, Kasimvayal, Devala)...',
    'places.filter_all': 'All Localities',
    'places.join_locality': 'Join Locality',
    'places.report_issue': 'Report Issue in Locality',
    'places.coordinator': 'Local Coordinator',
    'places.active_issues': 'Active Issues',
    'places.members': 'Residents',

    // Identity / Gudalur ID
    'id.title': 'The Gudalur Resident Identity',
    'id.subtitle': 'Your unique digital proof of community belonging and verified civic participation.',
    'id.card_title': 'RESIDENT CITIZEN CARD',
    'id.number_label': 'GUDALUR ID',
    'id.place_label': 'MY LOCALITY',
    'id.status_label': 'VERIFICATION TIER',
    'id.share_whatsapp': 'Share ID on WhatsApp',
    'id.download_card': 'Save Digital Card',
    'id.privacy_notice': 'Your personal phone number remains strictly private and encrypted.',

    // Civic Issues
    'issues.title': 'Civic Issue Engine',
    'issues.subtitle': 'Evidence-driven citizen reporting. Every pothole, broken streetlight, or water failure is logged with a permanent tracking ID and transparent status progression.',
    'issues.report_btn': 'Report Civic Issue',
    'issues.status_reported': 'Reported',
    'issues.status_verification': 'Verification',
    'issues.status_assigned': 'Assigned to Dept',
    'issues.status_action': 'Action in Progress',
    'issues.status_resolved': 'Resolved & Verified',

    // Wildlife
    'wildlife.title': 'Human-Wildlife Coexistence Hub',
    'wildlife.subtitle': 'Protecting human life and wild elephants through early warning, corridor intelligence, and rapid response coordination with Gudalur Forest Division.',
    'wildlife.log_sighting': 'Log Wildlife Sighting',
    'wildlife.active_corridors': 'Active Elephant Corridors',
    'wildlife.safety_guidelines': 'Safety Guidelines for Commuters',

    // Act for Gudalur / Petitions
    'act.title': 'Act For Gudalur',
    'act.subtitle': 'Lawful, peaceful, and evidence-based collective civic demands. Join thousands of verified residents to demand administrative action on essential infrastructure.',
    'act.sign_petition': 'Support This Demand',
    'act.already_supported': 'You Supported This Demand',
    'act.target_authority': 'Target Administrative Authority',
    'act.evidence_docket': 'Evidence Docket & Background',
    'act.govt_response': 'Official Government Response',

    // Government Grievance
    'govt.title': 'Government Action Directory',
    'govt.subtitle': 'Official Tamil Nadu and National grievance redressal portals, CM Helpline 1100, TANGEDCO Minnal, and Collectorate grievance workflows.',
    'govt.file_official': 'Submit Official Grievance',
    'govt.track_complaint': 'Track Official Complaint ID',

    // Story
    'story.title': 'The Story of Gudalur',
    'story.subtitle': 'A grounded historical documentary of our land, shola forests, indigenous tribes, plantation heritage, and united civic future.',
    'story.chapter': 'Chapter',

    // AI Guide
    'ai.title': 'AI Civic Guide & Crop Doctor',
    'ai.subtitle': 'Instant assistance on Gudalur administrative processes, transport timings, and agricultural diagnostics for tea, pepper, and ginger growers.',
    'ai.placeholder': 'Ask about bus routes, government grievance steps, or describe crop leaf symptoms...'
  },
  ta: {
    // Brand & Navigation
    'brand.title': 'VOICE OF GUDALUR',
    'brand.tagline': 'ஒரே பூமி. பல சமூகங்கள். ஒன்றுபட்ட மக்கள்.',
    'nav.manifesto': 'உரிமைக்குரல் பிரகடனம்',
    'nav.home': 'பிரகடனம்',
    'nav.hub': 'தகவல் மையம்',
    'nav.places': 'பகுதிகள்',
    'nav.live': 'கூடலூர் லைவ்',
    'nav.alerts': 'அவசர எச்சரிக்கை',
    'nav.issues': 'மக்கள் புகார்கள்',
    'nav.wildlife': 'வனவிலங்கு மையம்',
    'nav.petitions': 'கூடலூருக்கான குரல்',
    'nav.government': 'அரசு குறைதீர்ப்பு',
    'nav.bus': 'பேருந்து நேரம்',
    'nav.services': 'சேவைகள்',
    'nav.story': 'கூடலூர் வரலாறு',
    'nav.guide': 'ஏஐ வழிகாட்டி',
    'nav.id': 'கூடலூர் ஐடி',
    'nav.admin': 'நிர்வாகம்',
    'nav.join': 'இணையுங்கள்',

    // Hero Section
    'hero.badge': 'வாழும் தகவல் மற்றும் மக்கள் உரிமைத் தளம்',
    'hero.headline': 'ஒன்றுபட்ட கூடலூர்.',
    'hero.subheadline': 'ஓ\'வேலி முதல் நாடுகாணி வரை, தொரப்பள்ளி முதல் தேவாலா வரை — உங்கள் பகுதியோடு இணையுங்கள், மக்கள் பிரச்னைகளை பதிவு செய்யுங்கள், எச்சரிக்கைகளைப் பெறுங்கள்.',
    'hero.join_btn': 'உங்கள் கூடலூர் ஐடி பெறுங்கள்',
    'hero.explore_map': 'பகுதிகளைப் பாருங்கள்',
    'hero.active_residents': 'இணைந்த மக்கள்',
    'hero.verified_localities': 'சரிபார்க்கப்பட்ட பகுதிகள்',
    'hero.active_petitions': 'மக்கள் கோரிக்கைகள்',
    'hero.resolved_issues': 'பதிவு செய்யப்பட்ட புகார்கள்',

    // Gudalur Live
    'live.title': 'கூடலூர் லைவ்',
    'live.subtitle': 'நீலகிரி மேற்கு பீடபூமியின் வானிலை, சாலை நிலவரம் மற்றும் அவசர தகவல்கள்',
    'live.weather_temp': 'வெப்பநிலை',
    'live.weather_air': 'காற்று தரம் (AQI)',
    'live.weather_rain': 'மழை வாய்ப்பு',
    'live.weather_humidity': 'ஈரப்பதம்',
    'live.weather_wind': 'காற்றின் வேகம்',
    'live.ghat_status': 'மலைப்பாதை நிலவரம்',
    'live.night_traffic': 'முதுமலை இரவு போக்குவரத்து தடை: இரவு 9:00 – காலை 6:00 மணி வரை',
    'live.emergency_hotline': '24x7 நீலகிரி அவசர உதவி எண்கள்',

    // Localities
    'places.title': 'கூடலூர் பகுதிகள்',
    'places.subtitle': 'ஒவ்வொரு குடியிருப்பு பகுதியும் ஒரு நேரடி சமூக மையம். ஒருங்கிணைப்பாளர்கள், சேவைகள் மற்றும் கோரிக்கைகளை அறியுங்கள்.',
    'places.search_placeholder': 'பகுதியைத் தேடுங்கள் (எ.கா: எஸ்.எஸ். நகர், முதல் மைல், காசிம்வயல், தேவாலா)...',
    'places.filter_all': 'அனைத்து பகுதிகள்',
    'places.join_locality': 'பகுதியில் இணையுங்கள்',
    'places.report_issue': 'பகுதி பிரச்சனையைப் பதிவுசெய்',
    'places.coordinator': 'பகுதி ஒருங்கிணைப்பாளர்',
    'places.active_issues': 'நிலுவை பிரச்சனைகள்',
    'places.members': 'குடிமக்கள்',

    // Identity / Gudalur ID
    'id.title': 'கூடலூர் குடியுரிமை அடையாளம்',
    'id.subtitle': 'கூடலூர் சமூகத்தில் உங்கள் பங்களிப்பிற்கான பிரத்யேக டிஜிட்டல் அடையாள அட்டை.',
    'id.card_title': 'கூடலூர் குடியுரிமை அட்டை',
    'id.number_label': 'கூடலூர் ஐடி எண்',
    'id.place_label': 'எனது பகுதி',
    'id.status_label': 'சரிபார்ப்பு நிலை',
    'id.share_whatsapp': 'வாட்ஸ்அப்பில் பகிருங்கள்',
    'id.download_card': 'அட்டையை சேமிக்க',
    'id.privacy_notice': 'உங்கள் தொலைபேசி எண் பாதுகாப்பாக வைக்கப்படும், பொதுவெளியில் காட்டப்படாது.',

    // Civic Issues
    'issues.title': 'மக்கள் பிரச்சனை கண்காணிப்பு பிரிவு',
    'issues.subtitle': 'சாலைப் பழுது, குடிநீர் தட்டுப்பாடு, மின்தடை போன்ற பிரச்னைகளை ஆதாரத்துடன் பதிவு செய்து அரசு தீர்வை கண்காணிக்கலாம்.',
    'issues.report_btn': 'பிரச்சனையைப் பதிவு செய்க',
    'issues.status_reported': 'பதிவு செய்யப்பட்டது',
    'issues.status_verification': 'சரிபார்ப்பில்',
    'issues.status_assigned': 'துறைக்கு அனுப்பப்பட்டது',
    'issues.status_action': 'நடவடிக்கையில்',
    'issues.status_resolved': 'தீர்வு காணப்பட்டது',

    // Wildlife
    'wildlife.title': 'வனவிலங்கு & மனித சகவாழ்வு மையம்',
    'wildlife.subtitle': 'காட்டு யானைகள் மற்றும் மனித பாதுகாப்பிற்கான முன்கூட்டிய எச்சரிக்கை மற்றும் வனத்துறை கண்காணிப்பு பிரிவு.',
    'wildlife.log_sighting': 'யானை நடமாட்டத்தை பதிவிடுக',
    'wildlife.active_corridors': 'முக்கிய யானை வழித்தடங்கள்',
    'wildlife.safety_guidelines': 'பயணிகளுக்கான பாதுகாப்பு வழிகாட்டுதல்',

    // Act for Gudalur / Petitions
    'act.title': 'கூடலூருக்கான குரல் (கோரிக்கைகள்)',
    'act.subtitle': 'சட்டப்பூர்வ, அமைதியான மற்றும் ஆதாரபூர்வ கூட்டு மக்கள் மனுக்கள். அரசு மருத்துவமனை மேம்பாடு போன்ற முக்கிய கோரிக்கைகளுக்கு ஆதரவு தெரிவியுங்கள்.',
    'act.sign_petition': 'இக்கோரிக்கையை ஆதரிக்கிறேன்',
    'act.already_supported': 'நீங்கள் இக்கோரிக்கையை ஆதரித்துள்ளீர்கள்',
    'act.target_authority': 'தொடர்புடைய அரசுத் துறை',
    'act.evidence_docket': 'ஆதாரங்கள் & பின்னணி விவரம்',
    'act.govt_response': 'அரசின் அதிகாரப்பூர்வ பதில்',

    // Government Grievance
    'govt.title': 'அரசு குறைதீர்ப்பு வழிகாட்டி',
    'govt.subtitle': 'முதல்வரின் முகவரி (1100), மின்வாரிய மின்னகம், கூடலூர் நகராட்சி மற்றும் மாவட்ட ஆட்சியர் குறைதீர்ப்பு முகாம்கள்.',
    'govt.file_official': 'அரசு மனு தாக்கல் செய்ய',
    'govt.track_complaint': 'அரசு புகார் எண்ணைக் கண்காணிக்க',

    // Story
    'story.title': 'கூடலூரின் வரலாறு & மரபு',
    'story.subtitle': 'சோலை காடுகள், பூர்வகுடி மக்கள், தேயிலைத் தோட்டங்கள் மற்றும் கூடலூரின் கூட்டு வரலாறு.',
    'story.chapter': 'அத்தியாயம்',

    // AI Guide
    'ai.title': 'ஏஐ கூடலூர் வழிகாட்டி & பயிர் மருத்துவர்',
    'ai.subtitle': 'பேருந்து நேரம், அரசு குறைதீர்ப்பு வழிகள் மற்றும் தேயிலை/இஞ்சி பயிர் நோய் தடுப்பு ஆலோசனைகள் பெறுங்கள்.',
    'ai.placeholder': 'பேருந்து நேரம் அல்லது பயிர் அறிகுறிகளைப் பற்றி கேளுங்கள்...'
  },
  ml: {
    // Nav & Brand
    'brand.title': 'VOICE OF GUDALUR',
    'brand.tagline': 'ഒരു ദേശം. പല സമൂഹങ്ങൾ. ഒന്നിച്ച ജനത.',
    'nav.manifesto': 'അവകാശ പ്രകടനപത്രിക',
    'nav.home': 'പ്രഖ്യാപനം',
    'nav.hub': 'സിറ്റി ഹബ്',
    'nav.places': 'സ്ഥലങ്ങൾ',
    'nav.live': 'ഗൂഡല്ലൂർ ലൈവ്',
    'nav.alerts': 'അലേർട്ടുകൾ',
    'nav.issues': 'പ്രശ്നങ്ങൾ',
    'nav.wildlife': 'വന്യജീവി ഹബ്',
    'nav.petitions': 'പ്രവർത്തിക്കുക',
    'nav.government': 'പരാതികൾ',
    'nav.bus': 'ബസ് സമയങ്ങൾ',
    'nav.services': 'സേവനങ്ങൾ',
    'nav.story': 'ചരിത്രം',
    'nav.guide': 'എഐ ഗൈഡ്',
    'nav.id': 'ഗൂഡല്ലൂർ ഐഡി',
    'nav.admin': 'കൺസോൾ',
    'nav.join': 'ചേരുക',
    'hero.badge': 'ലൈവിംഗ് ഇന്റലിജൻസ് പ്ലാറ്റ്‌ഫോം',
    'hero.headline': 'ഐക്യ ഗൂഡല്ലൂർ.',
    'hero.subheadline': 'കാസിംവയൽ മുതൽ എസ്.എസ്. നഗർ വരെ, തൊരപ്പള്ളി മുതൽ ദേവാല വരെ — നിങ്ങളുടെ സ്ഥലവുമായി ബന്ധപ്പെടുക.',
    'hero.join_btn': 'ഗൂഡല്ലൂർ ഐഡി നേടുക',
    'hero.explore_map': 'സ്ഥലങ്ങൾ കാണുക',
    'hero.active_residents': 'രജിസ്റ്റർ ചെയ്തവർ',
    'hero.verified_localities': 'സ്ഥലങ്ങൾ',
    'hero.active_petitions': 'പരാതികൾ',
    'hero.resolved_issues': 'പരിഹരിച്ചവ',
    'live.title': 'ഗൂഡല്ലൂർ ലൈവ്',
    'live.subtitle': 'തത്സമയ കാലാവസ്ഥ, റോഡ് വിവരങ്ങൾ, സുരക്ഷാ മുന്നറിയിപ്പുകൾ',
    'places.title': 'സ്ഥലങ്ങൾ',
    'places.subtitle': 'ഓരോ പ്രദേശത്തെയും സേവനങ്ങളും വിവരങ്ങളും അറിയുക',
    'id.title': 'ഗൂഡല്ലൂർ ഐഡി',
    'id.subtitle': 'നിങ്ങളുടെ ഐഡന്റിറ്റി കാർഡ്',
    'issues.title': 'ജനകീയ പ്രശ്നങ്ങൾ',
    'issues.subtitle': 'റോഡ്, വെള്ളം, വൈദ്യുതി പ്രശ്നങ്ങൾ രേഖപ്പെടുത്തുക',
    'wildlife.title': 'വന്യജീവി സഹവർത്തിത്വം',
    'wildlife.subtitle': 'ആന സാന്നിധ്യ മുന്നറിയിപ്പുകൾ',
    'act.title': 'ഗൂഡല്ലൂരിനായി പ്രവർത്തിക്കുക',
    'act.subtitle': 'കൂട്ടായ ജനകീയ ആവശ്യങ്ങൾ',
    'govt.title': 'സർക്കാർ സഹായങ്ങൾ',
    'govt.subtitle': 'ഔദ്യോഗിക പരാതി പരിഹാര മാർഗങ്ങൾ',
    'story.title': 'ഗൂഡല്ലൂർ ചരിത്രം',
    'story.subtitle': 'നമ്മുടെ സംസ്കാരവും പാരമ്പര്യവും',
    'ai.title': 'എഐ ഗൈഡ്',
    'ai.subtitle': 'ചോദ്യങ്ങൾക്ക് ഉത്തരം നേടുക'
  },
  kn: {
    // Brand & Navigation
    'brand.title': 'VOICE OF GUDALUR',
    'brand.tagline': 'ಒಂದು ಭೂಮಿ. ಹಲವು ಸಮುದಾಯಗಳು. ಒಂದಾದ ಜನತೆ.',
    'nav.manifesto': 'ಬದುಕುವ ಹಕ್ಕು ಪ್ರಣಾಳಿಕೆ',
    'nav.home': 'ಪ್ರಣಾಳಿಕೆ',
    'nav.hub': 'ನಾಗರಿಕ ಮಾಹಿತಿ ಕೇಂದ್ರ',
    'nav.places': 'ಪ್ರದೇಶಗಳು',
    'nav.live': 'ಗೂಡಲೂರು ಲೈವ್',
    'nav.alerts': 'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    'nav.issues': 'ಜನರ ಸಮಸ್ಯೆಗಳು',
    'nav.wildlife': 'ವನ್ಯಜೀವಿ ಕೇಂದ್ರ',
    'nav.petitions': 'ಗೂಡಲೂರಿನ ಧ್ವನಿ',
    'nav.government': 'ಸರ್ಕಾರಿ ಪರಿಹಾರ',
    'nav.bus': 'ಬಸ್ ಸಮಯ',
    'nav.services': 'ಸೇವೆಗಳು',
    'nav.story': 'ಗೂಡಲೂರಿನ ಇತಿಹಾಸ',
    'nav.guide': 'ಎಐ ಮಾರ್ಗದರ್ಶಿ',
    'nav.id': 'ಗೂಡಲೂರು ಐಡಿ',
    'nav.admin': 'ಆಡಳಿತ',
    'nav.join': 'ಸೇರ್ಪಡೆಗೊಳ್ಳಿ',

    // Hero Section
    'hero.badge': 'ನೈಜ ಮಾಹಿತಿ ಮತ್ತು ನಾಗರಿಕ ಕ್ರಿಯಾ ವೇದಿಕೆ',
    'hero.headline': 'ಐಕ್ಯ ಗೂಡಲೂರು.',
    'hero.subheadline': 'ಓವೆಲಿಯಿಂದ ನಾಡುಗಾಣಿವರೆಗೆ, ತೊರಪಳ್ಳಿಯಿಂದ ದೇವಾಲದವರೆಗೆ — ನಿಮ್ಮ ಪ್ರದೇಶದೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ, ನೈಜ ಸಮಸ್ಯೆಗಳನ್ನು ದಾಖಲಿಸಿ, ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'hero.join_btn': 'ನಿಮ್ಮ ಗೂಡಲೂರು ಐಡಿ ಪಡೆಯಿರಿ',
    'hero.explore_map': 'ಪ್ರದೇಶಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'hero.active_residents': 'ನೊಂದಾಯಿತ ನಾಗರಿಕರು',
    'hero.verified_localities': 'ಪರಿಶೀಲಿತ ಪ್ರದೇಶಗಳು',
    'hero.active_petitions': 'ಸಕ್ರಿಯ ಬೇಡಿಕೆಗಳು',
    'hero.resolved_issues': 'ದಾಖಲಾದ ಸಮಸ್ಯೆಗಳು',

    // Gudalur Live
    'live.title': 'ಗೂಡಲೂರು ಲೈವ್',
    'live.subtitle': 'ನೀಲಗಿರಿ ಪಶ್ಚಿಮ ಪ್ರಸ್ಥಭೂಮಿಯ ನೈಜ ಹವಾಮಾನ, ರಸ್ತೆ ಪರಿಸ್ಥಿತಿ ಮತ್ತು ತುರ್ತು ಮಾಹಿತಿ',
    'live.weather_temp': 'ತಾಪಮಾನ',
    'live.weather_air': 'ವಾಯು ಗುಣಮಟ್ಟ (AQI)',
    'live.weather_rain': 'ಮಳೆಯ ಸಂಭವನೀಯತೆ',
    'live.weather_humidity': 'ಆರ್ದ್ರತೆ',
    'live.weather_wind': 'ಗಾಳಿಯ ವೇಗ',
    'live.ghat_status': 'ಘಾಟ್ ರಸ್ತೆಗಳ ಸ್ಥಿತಿ',
    'live.night_traffic': 'ಮುಡುಮಲೈ ರಾತ್ರಿ ಸಂಚಾರ ನಿಷೇಧ: ರಾತ್ರಿ 9:00 ರಿಂದ ಬೆಳಿಗ್ಗೆ 6:00 ರವರೆಗೆ',
    'live.emergency_hotline': '24x7 ನೀಲಗಿರಿ ತುರ್ತು ಸಹಾಯವಾಣಿ',

    // Localities
    'places.title': 'ಗೂಡಲೂರಿನ ಪ್ರದೇಶಗಳು',
    'places.subtitle': 'ಪ್ರತಿಯೊಂದು ಬಡಾವಣೆಯೂ ಒಂದು ಜೀವಂತ ಸಮುದಾಯ ಕೇಂದ್ರ. ಸ್ಥಳೀಯ ಸೇವೆಗಳು, ಸಂಯೋಜಕರು ಮತ್ತು ಸಕ್ರಿಯ ಬೇಡಿಕೆಗಳನ್ನು ತಿಳಿಯಿರಿ.',
    'places.search_placeholder': 'ಪ್ರದೇಶವನ್ನು ಹುಡುಕಿ (ಉದಾ: ಎಸ್.ಎಸ್. ನಗರ, ಫಸ್ಟ್ ಮೈಲ್, ಕಾಸಿಂವಯಲ್, ದೇವಾಲ)...',
    'places.filter_all': 'ಎಲ್ಲಾ ಪ್ರದೇಶಗಳು',
    'places.join_locality': 'ಪ್ರದೇಶಕ್ಕೆ ಸೇರಿ',
    'places.report_issue': 'ಸ್ಥಳೀಯ ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    'places.coordinator': 'ಸ್ಥಳೀಯ ಸಂಯೋಜಕರು',
    'places.active_issues': 'ಸಕ್ರಿಯ ಸಮಸ್ಯೆಗಳು',
    'places.members': 'ನಾಗರಿಕರು',

    // Identity / Gudalur ID
    'id.title': 'ಗೂಡಲೂರು ನಾಗರಿಕ ಗುರುತು',
    'id.subtitle': 'ಸಮುದಾಯದಲ್ಲಿ ನಿಮ್ಮ ಪಾಲ್ಗೊಳ್ಳುವಿಕೆಯ ಡಿಜಿಟಲ್ ಪುರಾವೆ ಮತ್ತು ಗುರುತಿನ ಚೀಟಿ.',
    'id.card_title': 'ಗೂಡಲೂರು ನಿವಾಸಿ ಗುರುತಿನ ಚೀಟಿ',
    'id.number_label': 'ಗೂಡಲೂರು ಐಡಿ ಸಂಖ್ಯೆ',
    'id.place_label': 'ನನ್ನ ಪ್ರದೇಶ',
    'id.status_label': 'ಪರಿಶೀಲನಾ ಹಂತ',
    'id.share_whatsapp': 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
    'id.download_card': 'ಕಾರ್ಡ್ ಉಳಿಸಿ',
    'id.privacy_notice': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ದೂರವಾಣಿ ಸಂಖ್ಯೆ ಸುರಕ್ಷಿತವಾಗಿರುತ್ತದೆ, ಸಾರ್ವಜನಿಕವಾಗಿ ಪ್ರದರ್ಶಿಸಲಾಗುವುದಿಲ್ಲ.',

    // Civic Issues
    'issues.title': 'ನಾಗರಿಕ ಸಮಸ್ಯೆ ನಿವಾರಣಾ ವ್ಯವಸ್ಥೆ',
    'issues.subtitle': 'ರಸ್ತೆ ಹಾನಿ, ಕುಡಿಯುವ ನೀರಿನ ಕೊರತೆ, ವಿದ್ಯುತ್ ವ್ಯತ್ಯಯ ಮುಂತಾದ ಸಮಸ್ಯೆಗಳನ್ನು ಸಾಕ್ಷ್ಯ ಸಮೇತ ದಾಖಲಿಸಿ ಸರ್ಕಾರದ ಪರಿಹಾರವನ್ನು ಗಮನಿಸಿ.',
    'issues.report_btn': 'ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ',
    'issues.status_reported': 'ವರದಿಯಾಗಿದೆ',
    'issues.status_verification': 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
    'issues.status_assigned': 'ಇಲಾಖೆಗೆ ನಿಯೋಜಿಸಲಾಗಿದೆ',
    'issues.status_action': 'ಕ್ರಮ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    'issues.status_resolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ',

    // Wildlife
    'wildlife.title': 'ಮಾನವ-ವನ್ಯಜೀವಿ ಸಹಬಾಳ್ವೆ ಕೇಂದ್ರ',
    'wildlife.subtitle': 'ಕಾಡಾನೆಗಳು ಮತ್ತು ಮಾನವ ಸುರಕ್ಷತೆಗಾಗಿ ಮುನ್ನೆಚ್ಚರಿಕೆ, ಕಾರಿಡಾರ್ ಮಾಹಿತಿ ಮತ್ತು ಅರಣ್ಯ ಇಲಾಖೆ ಸಮನ್ವಯ.',
    'wildlife.log_sighting': 'ವನ್ಯಜೀವಿ ಸಂಚಾರ ದಾಖಲಿಸಿ',
    'wildlife.active_corridors': 'ಸಕ್ರಿಯ ಆನೆ ಕಾರಿಡಾರ್‌ಗಳು',
    'wildlife.safety_guidelines': 'ಪ್ರಯಾಣಿಕರ ಸುರಕ್ಷತಾ ಮಾರ್ಗಸೂಚಿಗಳು',

    // Act for Gudalur / Petitions
    'act.title': 'ಗೂಡಲೂರಿನ ಒಗ್ಗಟ್ಟಿನ ಧ್ವನಿ',
    'act.subtitle': 'ಕಾನೂನುಬದ್ಧ, ಶಾಂತಿಯುತ ಮತ್ತು ಸಾಕ್ಷ್ಯಾಧಾರಿತ ಸಾಮೂಹಿಕ ನಾಗರಿಕ ಬೇಡಿಕೆಗಳು. ಅಗತ್ಯ ಮೂಲಸೌಕರ್ಯಗಳಿಗಾಗಿ ಸಾವಿರಾರು ನಾಗರಿಕರೊಂದಿಗೆ ಧ್ವನಿ ಎತ್ತಿ.',
    'act.sign_petition': 'ಈ ಬೇಡಿಕೆಯನ್ನು ಬೆಂಬಲಿಸಿ',
    'act.already_supported': 'ನೀವು ಈಗಾಗಲೇ ಬೆಂಬಲಿಸಿದ್ದೀರಿ',
    'act.target_authority': 'ಸಂಬಂಧಿತ ಸರ್ಕಾರಿ ಇಲಾಖೆ',
    'act.evidence_docket': 'ಸಾಕ್ಷ್ಯಗಳು ಮತ್ತು ಹಿನ್ನೆಲೆ ವಿವರ',
    'act.govt_response': 'ಸರ್ಕಾರದ ಅಧಿಕೃತ ಪ್ರತಿಕ್ರಿಯೆ',

    // Government Grievance
    'govt.title': 'ಸರ್ಕಾರಿ ಪರಿಹಾರ ಮಾರ್ಗದರ್ಶಿ',
    'govt.subtitle': 'ಮುಖ್ಯಮಂತ್ರಿಗಳ ಸಹಾಯವಾಣಿ 1100, ಮಿನ್ನಲ್ ವಿದ್ಯುತ್ ಪರಿಹಾರ, ಗೂಡಲೂರು ಪುರಸಭೆ ಮತ್ತು ಜಿಲ್ಲಾಧಿಕಾರಿಗಳ ಕುಂದುಕೊರತೆ ನಿವಾರಣೆ.',
    'govt.file_official': 'ಅಧಿಕೃತ ದೂರು ಸಲ್ಲಿಸಿ',
    'govt.track_complaint': 'ದೂರಿನ ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',

    // Story
    'story.title': 'ಗೂಡಲೂರಿನ ಇತಿಹಾಸ ಮತ್ತು ಪರಂಪರೆ',
    'story.subtitle': 'ಶೋಲಾ ಕಾಡುಗಳು, ಸ್ಥಳೀಯ ಬುಡಕಟ್ಟುಗಳು, ಚಹಾ ತೋಟಗಳು ಮತ್ತು ನಮ್ಮ ಐಕ್ಯ ನಾಗರಿಕ ಭವಿಷ್ಯ.',
    'story.chapter': 'ಅಧ್ಯಾಯ',

    // AI Guide
    'ai.title': 'ಎಐ ಗೂಡಲೂರು ಮಾರ್ಗದರ್ಶಿ ಮತ್ತು ಬೆಳೆ ವೈದ್ಯ',
    'ai.subtitle': 'ಬಸ್ ಸಮಯ, ಸರ್ಕಾರಿ ಪರಿಹಾರ ಕ್ರಮಗಳು ಮತ್ತು ಚಹಾ/ಕಾಳುಮೆಣಸು ಬೆಳೆ ರೋಗ ನಿರ್ಣಯಕ್ಕೆ ತ್ವರಿತ ನೆರವು.',
    'ai.placeholder': 'ಬಸ್ ಸಮಯ ಅಥವಾ ಕೃಷಿ ಬೆಳೆ ರೋಗ ಲಕ್ಷಣಗಳ ಬಗ್ಗೆ ಕೇಳಿ...'
  }
};

/** ── MVP page strings (menu, homepage, registration, about, corridors, sightings) ── */
const extraTranslations: Record<Language, Record<string, string>> = {
  en: {
    'mnu.title': 'MENU',
    'mnu.sign_petition': 'Sign Petition',
    'mnu.about': 'About the Movement',
    'mnu.corridors': 'Closed Corridors Map',
    'mnu.sightings': 'Animal Sightings',
    'mnu.replay': 'Replay Opening',
    'mnu.support': 'Your support is recorded — thank you!',
    'mnu.register': 'Register — Get Gudalur ID',
    'mnu.login': 'Login',
    'mnu.my_card': 'My Gudalur ID Card',
    'mnu.logout': 'Logout',

    'home.title': 'Right to Life Petition',
    'home.subtitle': 'Sign the petition submitted as a grievance to Mudhalvan Mugavari. Your Gudalur ID + UTC timestamp are recorded as your digital signature — verifiable by officials at any time.',
    'home.loading': 'Loading live count…',
    'home.live': '{n} verified signs — live',
    'home.need_register': 'You must register (get a Gudalur ID) before signing — it takes 20 seconds, no OTP needed.',
    'home.register_cta': 'Register & Get GDR ID',
    'home.signing_as': 'Signing as',
    'home.gdr': 'GDR ID',
    'home.location': 'Location',
    'home.timestamp': 'Timestamp',
    'home.sign_btn': 'Sign with my Verified GDR ID',
    'home.signing': 'Recording your verified signature…',
    'home.recorded': 'Signature recorded & verifiable',
    'home.batch': 'Batch #{n}',
    'home.copy_link': 'Copy verify link',
    'home.share_wa': 'Share on WhatsApp',
    'home.download': 'Download receipt',
    'home.by_place': 'Signs by Place — highest first',
    'home.dup_toast': "You've already signed — thank you for your support!",
    'home.signed_toast': 'Your support is recorded — thank you!',
    'home.pdf_fail': 'Could not generate the PDF receipt',

    'reg.title': 'Register — Get your Gudalur ID',
    'reg.subtitle': 'No OTP needed. Just your name, mobile number and place — one number, one registration.',
    'reg.name': 'Full Name',
    'reg.phone': 'Mobile Number',
    'reg.place': 'Your Place (Gudalur & Nilgiris)',
    'reg.pincode': 'Pincode {n} — filled automatically.',
    'reg.estate': 'Specific Estate / Village (Optional)',
    'reg.submit': 'Generate My Gudalur ID',
    'reg.submitting': 'Generating Gudalur ID…',
    'reg.already': 'Already registered? Use Login with your mobile number or Gudalur ID. Aadhaar verification arrives later.',
    'reg.welcome': 'Welcome! Your Gudalur ID: {n}',
    'reg.dup_phone': 'This phone number is already registered — please use Login instead.',
    'reg.fail': 'Registration failed. Please try again.',
    'reg.name_required': 'Please enter your full name',
    'reg.phone_required': 'Please enter a valid 10-digit mobile number',

    'abt.title': 'About the Movement',
    'abt.sub': 'Voice of Gudalur — a citizen-led civic platform for Gudalur, The Nilgiris.',
    'abt.why_title': 'Why Voice of Gudalur exists',
    'abt.why_1': 'Gudalur is the keystone ecological bridge of the Nilgiri Biosphere Reserve — home to over 6,000 wild elephants, tigers and leopards, and to the farming communities who live alongside them. When human life, wildlife movement and development all compete for the same narrow valley floor, the result is a system in conflict: night-time road closures, crop raids, injuries, and rising fear on both sides.',
    'abt.why_2': 'We believe the answer is not to push wildlife away or keep people out — it is to redesign the shared space the way the opening animation shows: a system of dedicated lanes. Safe, uninterrupted corridors for elephants and tigers; protected, dignified passage for every resident; and a single civic voice that carries our demands to the government desks that serve us.',
    'abt.why_3': 'Voice of Gudalur is that civic voice — a privacy-first, offline-first platform where you can register, sign petitions, see live support from every locality, track closed corridors, and follow the grievances sent to the Chief Minister\'s cell. One community, one voice, the right to life.',
    'abt.corr_title': 'Closed corridors, live',
    'abt.corr_sub': 'The 11 closed / restricted wildlife corridors around Gudalur on the map — forest gates, night-closure sections and elephant-fringe buffers.',
    'abt.grv_title': 'Grievance submitted — Mudhalvarin Mugavari',
    'abt.grv_sub': 'This grievance has been submitted to the Tamil Nadu Chief Minister\'s special grievance cell. View the full details on the official portal.',
    'abt.grv_btn': 'View Grievance Details (#18982473)',
    'abt.grv_note': 'The official portal does not allow embedding, so this opens on cmhelpline.tnega.org in a new tab.',
    'abt.support_title': 'Support this grievance — sign the petition',
    'abt.support_sub': 'Every verified signature strengthens this grievance. Add your voice now.',
    'abt.privacy': 'Privacy-first. Your phone number stays private and is never shown publicly. Zero passwords. Aadhaar verification arrives later.',
    'abt.sign_cta': 'Sign in Petition',

    'crr.title': 'Closed Corridors — Gudalur & Nilgiris',
    'crr.sub': '{n} closed / restricted wildlife corridor checkpoints around Gudalur — forest gates, night-closure sections and elephant-fringe buffers. Keep this list in sync with Gudalur Forest Division notifications.',

    'sght.title': 'Animal Sightings',
    'sght.sub': 'Sighting reports will open here.',
    'sght.btn': 'Sign the Petition',
  },
  ta: {
    'mnu.title': 'மெனு',
    'mnu.sign_petition': 'மனுவில் கையெழுத்திடு',
    'mnu.about': 'இயக்கம் பற்றி',
    'mnu.corridors': 'மூடப்பட்ட வன வழித்தடங்கள்',
    'mnu.sightings': 'வனவிலங்கு நடமாட்டம்',
    'mnu.replay': 'தொடக்க காட்சியை மீண்டும்',
    'mnu.support': 'உங்கள் ஆதரவு பதிவாகியது — நன்றி!',
    'mnu.register': 'பதிவு — கூடலூர் ஐடி பெறு',
    'mnu.login': 'உள்நுழை',
    'mnu.my_card': 'என் கூடலூர் ஐடி அட்டை',
    'mnu.logout': 'வெளியேறு',

    'home.title': 'வாழ்வுரிமை மனு',
    'home.subtitle': 'முதல்வர் முகவரியிடம் சமர்ப்பித்த மனுவில் கையெழுத்திடுங்கள். உங்கள் கூடலூர் ஐடி + UTC நேர முத்திரை உங்கள் டிஜிட்டல் கையெழுத்தாகப் பதிவாகும் — எப்போது வேண்டுமானாலும் அதிகாரிகளால் சரிபார்க்கலாம்.',
    'home.loading': 'நேரடி எண்ணிக்கை ஏற்றப்படுகிறது…',
    'home.live': '{n} சரிபார்க்கப்பட்ட கையெழுத்துகள் — நேரடி',
    'home.need_register': 'கையெழுத்திடுவதற்கு முன் பதிவு செய்ய வேண்டும் (கூடலூர் ஐடி) — 20 வினாடிகளில் முடியும், OTP தேவையில்லை.',
    'home.register_cta': 'பதிவு & GDR ஐடி பெறு',
    'home.signing_as': 'கையெழுத்திடுபவர்',
    'home.gdr': 'GDR ஐடி',
    'home.location': 'இடம்',
    'home.timestamp': 'நேர முத்திரை',
    'home.sign_btn': 'சரிபார்க்கப்பட்ட GDR ஐடியுடன் கையெழுத்திடு',
    'home.signing': 'உங்கள் சரிபார்க்கப்பட்ட கையெழுத்து பதிவாகிறது…',
    'home.recorded': 'கையெழுத்து பதிவாகி சரிபார்க்கக்கூடியது',
    'home.batch': 'தொகுதி #{n}',
    'home.copy_link': 'சரிபார்ப்பு இணைப்பை நகலெடு',
    'home.share_wa': 'வாட்ஸ்அப்பில் பகிர்',
    'home.download': 'ரசீது பதிவிறக்கு',
    'home.by_place': 'இடம் வாரியான கையெழுத்துகள் — அதிகமானது முதலில்',
    'home.dup_toast': 'நீங்கள் ஏற்கனவே கையெழுத்திட்டுள்ளீர்கள் — உங்கள் ஆதரவுக்கு நன்றி!',
    'home.signed_toast': 'உங்கள் ஆதரவு பதிவாகியது — நன்றி!',
    'home.pdf_fail': 'PDF ரசீதை உருவாக்க முடியவில்லை',

    'reg.title': 'பதிவு — உங்கள் கூடலூர் ஐடி பெறுக',
    'reg.subtitle': 'OTP தேவையில்லை. பெயர், கைபேசி எண் மற்றும் இடம் மட்டும் போதும் — ஒரு எண், ஒரே பதிவு.',
    'reg.name': 'முழு பெயர்',
    'reg.phone': 'கைபேசி எண்',
    'reg.place': 'உங்கள் இடம் (கூடலூர் & நீலகிரி)',
    'reg.pincode': 'அஞ்சல் குறியீடு {n} — தானாக நிரப்பப்படும்.',
    'reg.estate': 'குறிப்பிட்ட எஸ்டேட் / கிராமம் (விருப்பம்)',
    'reg.submit': 'என் கூடலூர் ஐடியை உருவாக்கு',
    'reg.submitting': 'கூடலூர் ஐடி உருவாகிறது…',
    'reg.already': 'ஏற்கனவே பதிவு செய்துவிட்டீர்களா? கைபேசி எண் அல்லது கூடலூர் ஐடி மூலம் உள்நுழையுங்கள். ஆதார் சரிபார்ப்பு விரைவில் வரும்.',
    'reg.welcome': 'வரவேற்கிறோம்! உங்கள் கூடலூர் ஐடி: {n}',
    'reg.dup_phone': 'இந்த கைபேசி எண் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது — உள்நுழைவைப் பயன்படுத்தவும்.',
    'reg.fail': 'பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    'reg.name_required': 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'reg.phone_required': 'சரியான 10 இலக்க கைபேசி எண்ணை உள்ளிடவும்',

    'abt.title': 'இயக்கம் பற்றி',
    'abt.sub': 'கூடலூர், நீலகிரி — மக்கள் தலைமையிலான நாகரிக தளம்.',
    'abt.why_title': 'கூடலூர் குரல் ஏன்?',
    'abt.why_1': 'கூடலூர் நீலகிரி உயிர்க்கோள காப்பகத்தின் முக்கிய சூழல் பாலமாகும் — 6,000 வன யானைகள், புலிகள், சிறுத்தைகள் மற்றும் அவற்றுடன் வாழும் விவசாய சமூகங்களின் இல்லம். மனித வாழ்க்கை, வனவிலங்கு இயக்கம், வளர்ச்சி ஆகியவை ஒரே குறுகிய பள்ளத்தாக்கிற்காக போட்டியிடும்போது, மோதல்கள் ஏற்படுகின்றன: இரவு சாலை மூடல்கள், பயிர் சேதம், காயங்கள், இருபுறமும் பயம்.',
    'abt.why_2': 'வனவிலங்குகளை விரட்டுவதும், மக்களை வெளியேற்றுவதும் தீர்வல்ல — பகிரப்பட்ட இடத்தை மறுவடிவமைப்பே தீர்வு: அர்ப்பணிக்கப்பட்ட வழித்தடங்கள். யானைகளுக்கும் புலிகளுக்கும் பாதுகாப்பான தொடர்ச்சியான பாதைகள்; ஒவ்வொரு குடியிருப்பாளருக்கும் பாதுகாக்கப்பட்ட, கண்ணியமான போக்குவரத்து; எங்கள் கோரிக்கைகளை அரசு மேசைகளுக்கு கொண்டு செல்லும் ஒற்றை மக்களின் குரல்.',
    'abt.why_3': 'கூடலூர் குரல் அந்த நாகரிக குரல்தான் — தனியுரிமை முதன்மை, ஆஃப்லைன்-ஆதரவு தளம். பதிவு, மனு கையெழுத்து, ஒவ்வொரு பகுதியின் நேரடி ஆதரவு, மூடிய வழித்தடங்கள் மற்றும் முதல்வர் முகவரிக்கு அனுப்பிய மனுக்களை பின்தொடரலாம். ஒரு சமூகம், ஒரு குரல், வாழ்வுரிமை.',
    'abt.corr_title': 'மூடப்பட்ட வன வழித்தடங்கள் — நேரடி வரைபடம்',
    'abt.corr_sub': 'கூடலூரைச் சுற்றியுள்ள 11 மூடப்பட்ட/கட்டுப்படுத்தப்பட்ட வன வழித்தடங்கள் — வன சாவடிகள், இரவு நேர மூடல்கள், யானை எல்லை மண்டலங்கள்.',
    'abt.grv_title': 'சமர்ப்பிக்கப்பட்ட மனு — முதல்வர் முகவரி',
    'abt.grv_sub': 'இந்த மனு தமிழ்நாடு முதல்வரின் சிறப்பு முகவரி அமைப்பில் சமர்ப்பிக்கப்பட்டுள்ளது. அதிகாரப்பூர்வ தளத்தில் முழு விவரங்களைப் பார்க்கவும்.',
    'abt.grv_btn': 'மனு விவரங்களைப் பார்க்கவும் (#18982473)',
    'abt.grv_note': 'அதிகாரப்பூர்வ தளம் உட்பொதிக்க அனுமதிப்பதில்லை — புதிய தாவலில் cmhelpline.tnega.org-இல் திறக்கும்.',
    'abt.support_title': 'இந்த மனுவை ஆதரிக்க — மனுவில் கையெழுத்திடுங்கள்',
    'abt.support_sub': 'ஒவ்வொரு சரிபார்க்கப்பட்ட கையெழுத்தும் இந்த மனுவை வலுப்படுத்துகிறது. இப்போதே உங்கள் குரலைச் சேருங்கள்.',
    'abt.privacy': 'தனியுரிமை முதன்மை. உங்கள் கைபேசி எண் தனிப்பட்டது, பொதுவில் காட்டப்படாது. எந்த கடவுச்சொல்லும் இல்லை. ஆதார் சரிபார்ப்பு விரைவில்.',
    'abt.sign_cta': 'மனுவில் கையெழுத்திடு',

    'crr.title': 'மூடப்பட்ட வன வழித்தடங்கள் — கூடலூர் & நீலகிரி',
    'crr.sub': 'கூடலூரைச் சுற்றியுள்ள {n} மூடப்பட்ட/கட்டுப்படுத்தப்பட்ட வன வழித்தடங்கள் — வன சாவடிகள், இரவு நேர மூடல்கள், யானை எல்லை மண்டலங்கள். வனத்துறை அறிவிப்புகளுடன் இணைத்து வைக்கவும்.',

    'sght.title': 'வனவிலங்கு நடமாட்டம்',
    'sght.sub': 'நடமாட்ட அறிக்கைகள் இங்கே திறக்கப்படும்.',
    'sght.btn': 'மனுவில் கையெழுத்திடு',
  },
  ml: {
    'mnu.title': 'മെനു',
    'mnu.sign_petition': 'പരാതിയിൽ ഒപ്പിടുക',
    'mnu.about': 'പ്രസ്ഥാനത്തെ കുറിച്ച്',
    'mnu.corridors': 'അടഞ്ഞ ഇടനാഴികൾ',
    'mnu.sightings': 'വന്യജീവി സാന്നിധ്യം',
    'mnu.replay': 'തുടക്ക കാഴ്ച വീണ്ടും',
    'mnu.support': 'നിങ്ങളുടെ പിന്തുണ രേഖപ്പെടുത്തി — നന്ദി!',
    'mnu.register': 'രജിസ്റ്റർ — ഗൂഡല്ലൂർ ഐഡി നേടുക',
    'mnu.login': 'ലോഗിൻ',
    'mnu.my_card': 'എന്റെ ഗൂഡല്ലൂർ ഐഡി കാർഡ്',
    'mnu.logout': 'പുറത്തുകടക്കുക',

    'home.title': 'ജീവൻ അവകാശ പരാതി',
    'home.subtitle': 'മുഖ്യമന്ത്രിയുടെ മുഖവുരയിൽ സമർപ്പിച്ച പരാതിയിൽ ഒപ്പിടുക. നിങ്ങളുടെ ഗൂഡല്ലൂർ ഐഡി + UTC സമയമുദ്ര ഡിജിറ്റൽ ഒപ്പായി രേഖപ്പെടുത്തും — എപ്പോൾ വേണമെങ്കിലും ഉദ്യോഗസ്ഥർക്ക് പരിശോധിക്കാം.',
    'home.loading': 'തത്സമയ എണ്ണം ലോഡ് ചെയ്യുന്നു…',
    'home.live': '{n} പരിശോധിച്ച ഒപ്പുകൾ — തത്സമയം',
    'home.need_register': 'ഒപ്പിടുന്നതിന് മുമ്പ് രജിസ്റ്റർ ചെയ്യണം (ഗൂഡല്ലൂർ ഐഡി) — 20 സെക്കൻഡ് മതി, OTP വേണ്ട.',
    'home.register_cta': 'രജിസ്റ്റർ & GDR ഐഡി നേടുക',
    'home.signing_as': 'ഒപ്പിടുന്നത്',
    'home.gdr': 'GDR ഐഡി',
    'home.location': 'സ്ഥലം',
    'home.timestamp': 'സമയമുദ്ര',
    'home.sign_btn': 'പരിശോധിച്ച GDR ഐഡി ഉപയോഗിച്ച് ഒപ്പിടുക',
    'home.signing': 'നിങ്ങളുടെ പരിശോധിച്ച ഒപ്പ് രേഖപ്പെടുത്തുന്നു…',
    'home.recorded': 'ഒപ്പ് രേഖപ്പെടുത്തി & പരിശോധിക്കാവുന്നത്',
    'home.batch': 'ബാച്ച് #{n}',
    'home.copy_link': 'പരിശോധന ലിങ്ക് പകർത്തുക',
    'home.share_wa': 'വാട്സ്ആപ്പിൽ പങ്കിടുക',
    'home.download': 'രസീത് ഡൗൺലോഡ്',
    'home.by_place': 'സ്ഥലം അനുസരിച്ചുള്ള ഒപ്പുകൾ — ഏറ്റവും കൂടുതൽ ആദ്യം',
    'home.dup_toast': 'നിങ്ങൾ ഇതിനകം ഒപ്പിട്ടു — നിങ്ങളുടെ പിന്തുണയ്ക്ക് നന്ദി!',
    'home.signed_toast': 'നിങ്ങളുടെ പിന്തുണ രേഖപ്പെടുത്തി — നന്ദി!',
    'home.pdf_fail': 'PDF രസീത് സൃഷ്ടിക്കാൻ കഴിഞ്ഞില്ല',

    'reg.title': 'രജിസ്റ്റർ — നിങ്ങളുടെ ഗൂഡല്ലൂർ ഐഡി നേടുക',
    'reg.subtitle': 'OTP ആവശ്യമില്ല. പേര്, മൊബൈൽ നമ്പർ, സ്ഥലം മാത്രം — ഒരു നമ്പർ, ഒരു രജിസ്ട്രേഷൻ.',
    'reg.name': 'മുഴുവൻ പേര്',
    'reg.phone': 'മൊബൈൽ നമ്പർ',
    'reg.place': 'നിങ്ങളുടെ സ്ഥലം (ഗൂഡല്ലൂർ & നീലഗിരി)',
    'reg.pincode': 'പിൻകോഡ് {n} — യാന്ത്രികമായി നിറയ്ക്കുന്നു.',
    'reg.estate': 'പ്രത്യേക എസ്റ്റേറ്റ് / ഗ്രാമം (ഓപ്ഷണൽ)',
    'reg.submit': 'എന്റെ ഗൂഡല്ലൂർ ഐഡി സൃഷ്ടിക്കുക',
    'reg.submitting': 'ഗൂഡല്ലൂർ ഐഡി സൃഷ്ടിക്കുന്നു…',
    'reg.already': 'ഇതിനകം രജിസ്റ്റർ ചെയ്തോ? മൊബൈൽ നമ്പർ അല്ലെങ്കിൽ ഗൂഡല്ലൂർ ഐഡി ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക. ആധാർ പരിശോധന പിന്നീട് വരും.',
    'reg.welcome': 'സ്വാഗതം! നിങ്ങളുടെ ഗൂഡല്ലൂർ ഐഡി: {n}',
    'reg.dup_phone': 'ഈ മൊബൈൽ നമ്പർ ഇതിനകം രജിസ്റ്റർ ചെയ്തു — ലോഗിൻ ഉപയോഗിക്കുക.',
    'reg.fail': 'രജിസ്ട്രേഷൻ പരാജയപ്പെട്ടു. വീണ്ടും ശ്രമിക്കുക.',
    'reg.name_required': 'നിങ്ങളുടെ മുഴുവൻ പേര് നൽകുക',
    'reg.phone_required': 'സാധുവായ 10 അക്ക മൊബൈൽ നമ്പർ നൽകുക',

    'abt.title': 'പ്രസ്ഥാനത്തെ കുറിച്ച്',
    'abt.sub': 'ഗൂഡല്ലൂർ, നീലഗിരി — ജനകീയ പൗരവേദി.',
    'abt.why_title': 'എന്തുകൊണ്ട് ഗൂഡല്ലൂർ ശബ്ദം',
    'abt.why_1': 'നീലഗിരി ബയോസ്ഫിയർ റിസർവിന്റെ പ്രധാന പാരിസ്ഥിതിക പാലമാണ് ഗൂഡല്ലൂർ — 6,000-ത്തിലധികം വന്യ ആനകളും, പുലികളും, കടുവകളും, അവരോടൊപ്പം കഴിയുന്ന കർഷക സമൂഹങ്ങളുടെയും ഭവനം. മനുഷ്യജീവൻ, വന്യജീവി സഞ്ചാരം, വികസനം എന്നിവ ഒരേ ഇടുങ്ങിയ താഴ്വരയ്ക്കായി മത്സരിക്കുമ്പോൾ ഏറ്റുമുട്ടൽ സംഭവിക്കുന്നു: രാത്രി റോഡ് അടയ്ക്കൽ, വിള നാശം, പരിക്കുകൾ, ഇരുവശത്തും ഭയം.',
    'abt.why_2': 'വന്യജീവികളെ അകറ്റുകയോ ആളുകളെ പുറത്താക്കുകയോ അല്ല പരിഹാരം — പങ്കിട്ട ഇടം മാറ്റിരൂപകൽപ്പന ചെയ്യുക എന്നതാണ്, തുടക്ക കാഴ്ചയിൽ കാണിച്ചതുപോലെ: പ്രത്യേക പാതകൾ. ആനകൾക്കും പുലികൾക്കും സുരക്ഷിതമായ തുടർച്ചയായ ഇടനാഴികൾ; ഓരോ നിവാസിക്കും സംരക്ഷിതവും മാന്യവുമായ പാത; നമ്മുടെ ആവശ്യങ്ങൾ സർക്കാർ മേശകളിലെത്തിക്കുന്ന ഒരൊറ്റ ജനകീയ ശബ്ദം.',
    'abt.why_3': 'ഗൂഡല്ലൂർ ശബ്ദം അതാണ് — സ്വകാര്യത-പ്രധാന, ഓഫ്ലൈൻ-സൗഹൃദ വേദി. രജിസ്റ്റർ ചെയ്യാം, പരാതിയിൽ ഒപ്പിടാം, ഓരോ സ്ഥലത്തിന്റെയും തത്സമയ പിന്തുണ കാണാം, അടഞ്ഞ ഇടനാഴികൾ പിന്തുടരാം, മുഖ്യമന്ത്രിയുടെ മുഖവുരയ്ക്ക് അയച്ച പരാതികൾ നിരീക്ഷിക്കാം. ഒരു സമൂഹം, ഒരു ശബ്ദം, ജീവിക്കാനുള്ള അവകാശം.',
    'abt.corr_title': 'അടഞ്ഞ ഇടനാഴികൾ — തത്സമയ ഭൂപടം',
    'abt.corr_sub': 'ഗൂഡല്ലൂരിന് ചുറ്റുമുള്ള 11 അടഞ്ഞ/നിയന്ത്രിത വന്യജീവി ഇടനാഴികൾ — ഫോറസ്റ്റ് ഗേറ്റുകൾ, രാത്രി അടയ്ക്കൽ, ആന അതിർത്തി മേഖലകൾ.',
    'abt.grv_title': 'സമർപ്പിച്ച പരാതി — മുഖ്യമന്ത്രിയുടെ മുഖവുര',
    'abt.grv_sub': 'ഈ പരാതി തമിഴ്നാട് മുഖ്യമന്ത്രിയുടെ പ്രത്യേക പരാതി സംവിധാനത്തിൽ സമർപ്പിച്ചു. ഔദ്യോഗിക പോർട്ടലിൽ മുഴുവൻ വിവരങ്ങൾ കാണുക.',
    'abt.grv_btn': 'പരാതി വിശദാംശങ്ങൾ കാണുക (#18982473)',
    'abt.grv_note': 'ഔദ്യോഗിക പോർട്ടൽ എംബഡ് അനുവദിക്കുന്നില്ല — പുതിയ ടാബിൽ cmhelpline.tnega.org-ൽ തുറക്കും.',
    'abt.support_title': 'ഈ പരാതിയെ പിന്തുണയ്ക്കാൻ — പരാതിയിൽ ഒപ്പിടുക',
    'abt.support_sub': 'ഓരോ പരിശോധിച്ച ഒപ്പും ഈ പരാതിയെ ശക്തിപ്പെടുത്തുന്നു. ഇപ്പോൾ തന്നെ ചേരൂ.',
    'abt.privacy': 'സ്വകാര്യത പ്രധാനം. നിങ്ങളുടെ മൊബൈൽ നമ്പർ സ്വകാര്യമാണ്, പരസ്യമായി കാണിക്കില്ല. പാസ്വേഡുകളില്ല. ആധാർ പരിശോധന പിന്നീട്.',
    'abt.sign_cta': 'പരാതിയിൽ ഒപ്പിടുക',

    'crr.title': 'അടഞ്ഞ ഇടനാഴികൾ — ഗൂഡല്ലൂർ & നീലഗിരി',
    'crr.sub': 'ഗൂഡല്ലൂരിന് ചുറ്റുമുള്ള {n} അടഞ്ഞ/നിയന്ത്രിത വന്യജീവി ഇടനാഴികൾ — ഫോറസ്റ്റ് ഗേറ്റുകൾ, രാത്രി അടയ്ക്കൽ, ആന അതിർത്തി മേഖലകൾ. വനം വകുപ്പ് അറിയിപ്പുകളുമായി പൊരുത്തപ്പെടുത്തുക.',

    'sght.title': 'വന്യജീവി സാന്നിധ്യം',
    'sght.sub': 'സാന്നിധ്യ റിപ്പോർട്ടുകൾ ഇവിടെ തുറക്കും.',
    'sght.btn': 'പരാതിയിൽ ഒപ്പിടുക',
  },
  kn: {
    'mnu.title': 'ಮೆನು',
    'mnu.sign_petition': 'ಅರ್ಜಿಗೆ ಸಹಿ ಹಾಕಿ',
    'mnu.about': 'ಚಳವಳಿಯ ಬಗ್ಗೆ',
    'mnu.corridors': 'ಮುಚ್ಚಿದ ಕಾರಿಡಾರ್ಗಳು',
    'mnu.sightings': 'ವನ್ಯಜೀವಿ ಸಂಚಾರ',
    'mnu.replay': 'ಆರಂಭಿಕ ಕಥೆಯನ್ನು ಮತ್ತೆ',
    'mnu.support': 'ನಿಮ್ಮ ಬೆಂಬಲ ದಾಖಲಾಗಿದೆ — ಧನ್ಯವಾದಗಳು!',
    'mnu.register': 'ನೋಂದಣಿ — ಗೂಡಲೂರು ಐಡಿ ಪಡೆಯಿರಿ',
    'mnu.login': 'ಲಾಗಿನ್',
    'mnu.my_card': 'ನನ್ನ ಗೂಡಲೂರು ಐಡಿ ಕಾರ್ಡ್',
    'mnu.logout': 'ನಿರ್ಗಮಿಸಿ',

    'home.title': 'ಜೀವನ ಹಕ್ಕು ಅರ್ಜಿ',
    'home.subtitle': 'ಮುಖ್ಯಮಂತ್ರಿಗಳ ಮುಖವರಿಗೆ ಸಲ್ಲಿಸಿದ ಅರ್ಜಿಗೆ ಸಹಿ ಹಾಕಿ. ನಿಮ್ಮ ಗೂಡಲೂರು ಐಡಿ + UTC ಸಮಯಮುದ್ರೆ ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಸಹಿಯಾಗಿ ದಾಖಲಾಗುತ್ತದೆ — ಯಾವಾಗ ಬೇಕಾದರೂ ಅಧಿಕಾರಿಗಳು ಪರಿಶೀಲಿಸಬಹುದು.',
    'home.loading': 'ನೈಜ ಸಂಖ್ಯೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
    'home.live': '{n} ಪರಿಶೀಲಿತ ಸಹಿಗಳು — ನೇರ',
    'home.need_register': 'ಸಹಿ ಹಾಕುವ ಮೊದಲು ನೋಂದಣಿ (ಗೂಡಲೂರು ಐಡಿ) — 20 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಆಗುತ್ತದೆ, OTP ಬೇಡ.',
    'home.register_cta': 'ನೋಂದಣಿ & GDR ಐಡಿ ಪಡೆಯಿರಿ',
    'home.signing_as': 'ಸಹಿ ಹಾಕುತ್ತಿರುವವರು',
    'home.gdr': 'GDR ಐಡಿ',
    'home.location': 'ಸ್ಥಳ',
    'home.timestamp': 'ಸಮಯಮುದ್ರೆ',
    'home.sign_btn': 'ಪರಿಶೀಲಿತ GDR ಐಡಿಯಲ್ಲಿ ಸಹಿ ಹಾಕಿ',
    'home.signing': 'ನಿಮ್ಮ ಪರಿಶೀಲಿತ ಸಹಿ ದಾಖಲಾಗುತ್ತಿದೆ…',
    'home.recorded': 'ಸಹಿ ದಾಖಲಾಗಿದೆ & ಪರಿಶೀಲಿಸಬಹುದಾಗಿದೆ',
    'home.batch': 'ಬ್ಯಾಚ್ #{n}',
    'home.copy_link': 'ಪರಿಶೀಲನಾ ಲಿಂಕ್ ನಕಲಿಸಿ',
    'home.share_wa': 'ವಾಟ್ಸಾಪ್ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
    'home.download': 'ಹುಂಡಿ (ಸ್ಲಿಪ್) ಡೌನ್ಲೋಡ್',
    'home.by_place': 'ಸ್ಥಳವಾರು ಸಹಿಗಳು — ಹೆಚ್ಚಿನದು ಮೊದಲು',
    'home.dup_toast': 'ನೀವು ಈಗಾಗಲೇ ಸಹಿ ಹಾಕಿದ್ದೀರಿ — ನಿಮ್ಮ ಬೆಂಬಲಕ್ಕೆ ಧನ್ಯವಾದಗಳು!',
    'home.signed_toast': 'ನಿಮ್ಮ ಬೆಂಬಲ ದಾಖಲಾಗಿದೆ — ಧನ್ಯವಾದಗಳು!',
    'home.pdf_fail': 'PDF ಹುಂಡಿಯನ್ನು ರಚಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',

    'reg.title': 'ನೋಂದಣಿ — ನಿಮ್ಮ ಗೂಡಲೂರು ಐಡಿ ಪಡೆಯಿರಿ',
    'reg.subtitle': 'OTP ಅಗತ್ಯವಿಲ್ಲ. ಹೆಸರು, ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಮತ್ತು ಸ್ಥಳ ಮಾತ್ರ — ಒಂದು ಸಂಖ್ಯೆ, ಒಂದು ನೋಂದಣಿ.',
    'reg.name': 'ಪೂರ್ಣ ಹೆಸರು',
    'reg.phone': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    'reg.place': 'ನಿಮ್ಮ ಸ್ಥಳ (ಗೂಡಲೂರು & ನೀಲಗಿರಿ)',
    'reg.pincode': 'ಪಿನ್ ಕೋಡ್ {n} — ಸ್ವಯಂಚಾಲಿತವಾಗಿ ತುಂಬುತ್ತದೆ.',
    'reg.estate': 'ನಿರ್ದಿಷ್ಟ ಎಸ್ಟೇಟ್ / ಗ್ರಾಮ (ಐಚ್ಛಿಕ)',
    'reg.submit': 'ನನ್ನ ಗೂಡಲೂರು ಐಡಿ ರಚಿಸಿ',
    'reg.submitting': 'ಗೂಡಲೂರು ಐಡಿ ರಚಿಸಲಾಗುತ್ತಿದೆ…',
    'reg.already': 'ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಿದ್ದೀರಾ? ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಅಥವಾ ಗೂಡಲೂರು ಐಡಿಯಿಂದ ಲಾಗಿನ್ ಆಗಿ. ಆಧಾರ್ ಪರಿಶೀಲನೆ ನಂತರ ಬರಲಿದೆ.',
    'reg.welcome': 'ಸ್ವಾಗತ! ನಿಮ್ಮ ಗೂಡಲೂರು ಐಡಿ: {n}',
    'reg.dup_phone': 'ಈ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ — ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಬಳಸಿ.',
    'reg.fail': 'ನೋಂದಣಿ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'reg.name_required': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    'reg.phone_required': 'ಸರಿಯಾದ 10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',

    'abt.title': 'ಚಳವಳಿಯ ಬಗ್ಗೆ',
    'abt.sub': 'ಗೂಡಲೂರು, ನೀಲಗಿರಿ — ಜನರ ನೇತೃತ್ವದ ನಾಗರಿಕ ವೇದಿಕೆ.',
    'abt.why_title': 'ಗೂಡಲೂರು ಧ್ವನಿ ಏಕೆ ಬೇಕು',
    'abt.why_1': 'ಗೂಡಲೂರು ನೀಲಗಿರಿ ಜೀವಗೋಳ ಮೀಸಲು ಪ್ರದೇಶದ ಪ್ರಮುಖ ಪರಿಸರ ಸೇತುವೆ — 6,000 ಕ್ಕೂ ಹೆಚ್ಚು ಕಾಡಾನೆಗಳು, ಹುಲಿಗಳು, ಚಿರತೆಗಳು ಮತ್ತು ಅವುಗಳೊಂದಿಗೆ ವಾಸಿಸುವ ರೈತ ಸಮುದಾಯಗಳ ನೆಲೆ. ಮಾನವ ಜೀವನ, ವನ್ಯಜೀವಿ ಚಲನೆ, ಅಭಿವೃದ್ಧಿ ಒಂದೇ ಕಿರಿದಾದ ಕಣಿವೆಗಾಗಿ ಸ್ಪರ್ಧಿಸಿದಾಗ ಘರ್ಷಣೆ ಉಂಟಾಗುತ್ತದೆ: ರಾತ್ರಿ ರಸ್ತೆ ಮುಚ್ಚುವಿಕೆ, ಬೆಳೆ ನಾಶ, ಗಾಯಗಳು, ಎರಡೂ ಕಡೆ ಭಯ.',
    'abt.why_2': 'ವನ್ಯಜೀವಿಗಳನ್ನು ದೂರ ಮಾಡುವುದು ಅಥವಾ ಜನರನ್ನು ಹೊರಗಿಡುವುದು ಪರಿಹಾರವಲ್ಲ — ಹಂಚಿಕೊಂಡ ಜಾಗವನ್ನು ಮರುವಿನ್ಯಾಸ ಮಾಡುವುದೇ ಪರಿಹಾರ, ಆರಂಭ ಚಿತ್ರಕಥೆಯಲ್ಲಿ ತೋರಿಸಿದಂತೆ: ಸಮರ್ಪಿತ ಸಾಲುಗಳ ವ್ಯವಸ್ಥೆ. ಆನೆಗಳು ಮತ್ತು ಹುಲಿಗಳಿಗೆ ಸುರಕ್ಷಿತ, ತಡೆರಹಿತ ಕಾರಿಡಾರ್ಗಳು; ಪ್ರತಿ ನಿವಾಸಿಗೆ ರಕ್ಷಿತ, ಗೌರವಯುತ ಮಾರ್ಗ; ನಮ್ಮ ಬೇಡಿಕೆಗಳನ್ನು ಸರ್ಕಾರಿ ಮೇಜುಗಳಿಗೆ ತಲುಪಿಸುವ ಒಂದೇ ಜನತೆಯ ಧ್ವನಿ.',
    'abt.why_3': 'ಗೂಡಲೂರು ಧ್ವನಿ ಅದೇ ನಾಗರಿಕ ಧ್ವನಿ — ಗೌಪ್ಯತೆ-ಮೊದಲ, ಆಫ್ಲೈನ್-ಸ್ನೇಹಿ ವೇದಿಕೆ. ನೋಂದಣಿ, ಸಹಿ, ಪ್ರತಿ ಪ್ರದೇಶದ ನೇರ ಬೆಂಬಲ, ಮುಚ್ಚಿದ ಕಾರಿಡಾರ್ಗಳು ಮತ್ತು ಮುಖ್ಯಮಂತ್ರಿಗಳಿಗೆ ಸಲ್ಲಿಸಿದ ದೂರುಗಳನ್ನು ಅನುಸರಿಸಬಹುದು. ಒಂದು ಸಮುದಾಯ, ಒಂದು ಧ್ವನಿ, ಬದುಕುವ ಹಕ್ಕು.',
    'abt.corr_title': 'ಮುಚ್ಚಿದ ಕಾರಿಡಾರ್ಗಳು — ನೇರ ನಕ್ಷೆ',
    'abt.corr_sub': 'ಗೂಡಲೂರು ಸುತ್ತಮುತ್ತಲಿನ 11 ಮುಚ್ಚಿದ/ನಿರ್ಬಂಧಿತ ವನ್ಯಜೀವಿ ಕಾರಿಡಾರ್ಗಳು — ವನ ಚೆಕ್ಪೋಸ್ಟ್ಗಳು, ರಾತ್ರಿ ಮುಚ್ಚುವಿಕೆಗಳು, ಆನೆ ಗಡಿ ವಲಯಗಳು.',
    'abt.grv_title': 'ಸಲ್ಲಿಸಿದ ದೂರು — ಮುಖ್ಯಮಂತ್ರಿಗಳ ಮುಖವರಿ',
    'abt.grv_sub': 'ಈ ದೂರನ್ನು ತಮಿಳುನಾಡು ಮುಖ್ಯಮಂತ್ರಿಗಳ ವಿಶೇಷ ದೂರು ಕೋಶಕ್ಕೆ ಸಲ್ಲಿಸಲಾಗಿದೆ. ಅಧಿಕೃತ ಪೋರ್ಟಲ್ನಲ್ಲಿ ಪೂರ್ಣ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ.',
    'abt.grv_btn': 'ದೂರಿನ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ (#18982473)',
    'abt.grv_note': 'ಅಧಿಕೃತ ಪೋರ್ಟಲ್ ಎಂಬೆಡ್ ಅನುಮತಿಸುವುದಿಲ್ಲ — ಹೊಸ ಟ್ಯಾಬ್ನಲ್ಲಿ cmhelpline.tnega.org ನಲ್ಲಿ ತೆರೆಯುತ್ತದೆ.',
    'abt.support_title': 'ಈ ದೂರನ್ನು ಬೆಂಬಲಿಸಲು — ಅರ್ಜಿಗೆ ಸಹಿ ಹಾಕಿ',
    'abt.support_sub': 'ಪ್ರತಿ ಪರಿಶೀಲಿತ ಸಹಿಯೂ ಈ ದೂರನ್ನು ಬಲಪಡಿಸುತ್ತದೆ. ಈಗಲೇ ಧ್ವನಿ ಸೇರಿಸಿ.',
    'abt.privacy': 'ಗೌಪ್ಯತೆ ಪ್ರಮುಖ. ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಖಾಸಗಿಯಾಗಿರುತ್ತದೆ, ಸಾರ್ವಜನಿಕವಾಗಿ ತೋರಿಸಲಾಗುವುದಿಲ್ಲ. ಪಾಸ್ವರ್ಡ್ ಇಲ್ಲ. ಆಧಾರ್ ಪರಿಶೀಲನೆ ನಂತರ.',
    'abt.sign_cta': 'ಅರ್ಜಿಗೆ ಸಹಿ ಹಾಕಿ',

    'crr.title': 'ಮುಚ್ಚಿದ ಕಾರಿಡಾರ್ಗಳು — ಗೂಡಲೂರು & ನೀಲಗಿರಿ',
    'crr.sub': 'ಗೂಡಲೂರು ಸುತ್ತಮುತ್ತಲಿನ {n} ಮುಚ್ಚಿದ/ನಿರ್ಬಂಧಿತ ವನ್ಯಜೀವಿ ಕಾರಿಡಾರ್ಗಳು — ವನ ಚೆಕ್ಪೋಸ್ಟ್ಗಳು, ರಾತ್ರಿ ಮುಚ್ಚುವಿಕೆಗಳು, ಆನೆ ಗಡಿ ವಲಯಗಳು. ವನ ಇಲಾಖೆ ಅಧಿಸೂಚನೆಗಳೊಂದಿಗೆ ಪಟ್ಟಿಯನ್ನು ಅಪ್ಡೇಟ್ ಮಾಡಿ.',

    'sght.title': 'ವನ್ಯಜೀವಿ ಸಂಚಾರ',
    'sght.sub': 'ಸಂಚಾರ ವರದಿಗಳು ಇಲ್ಲಿ ತೆರೆಯುತ್ತವೆ.',
    'sght.btn': 'ಅರ್ಜಿಗೆ ಸಹಿ ಹಾಕಿ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() => {
    return (localStorage.getItem('VoiceOfGudalur_lang') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('VoiceOfGudalur_lang', lang);
  }, [lang]);

  const t = (key: string) => {
    return translations[lang]?.[key] || extraTranslations[lang]?.[key] || extraTranslations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
